name: DO Workflow
on:
  push:
    branches: [ master ]
jobs:
  master_deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set current_timestamp
      run: |
          echo "current_timestamp=`date '+%y%m%d%H%M%S'`" >> $GITHUB_ENV
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        version: 1
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: neplk.com
        username: achala
        key: ${{secrets.DO_SSH}}
        port: 22
        source: "."
        target: "/var/www/neplk.com/public_html/releases/$TIMESTAMP/${{ env.current_timestamp }}"
    - name: Creating symlink
      uses: appleboy/ssh-action@master
      with: 
        host: neplk.com
        username: achala
        key: ${{secrets.DO_SSH}}
        port: 22
        script: |
          ln -sfn /var/www/neplk.com/public_html/releases/$TIMESTAMP/${{ env.current_timestamp }} /var/www/neplk.com/public_html/releases/$TIMESTAMP/current